services:
    nginx:
      build:
        context: ./docker/nginx
      depends_on:
        - app
      ports:
        - 80:80
      volumes:
        - ./:/src

    app:
      build:
        context: ./docker/php
      depends_on:
        - mysql
      volumes:
        - ./:/src
        - /src/node_modules
        - /src/vendor
        - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      networks:
        - app-network

    mysql:
      image: mysql:8.0.33
      command: --max_allowed_packet=32505856
      volumes:
        - ./docker/mysql:/var/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=local
      ports:
        - 3306:3306
      networks:
        - app-network

    schemaspy:
      build: ./docker/schemaspy
      depends_on:
          - mysql
      volumes:
      - ./documents/schemaspy:/documents/schemaspy

networks:
  app-network:
    driver: bridge