# SchemaspyでER図を生成してS3にアップロード
name: schemaspy

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - feature/CreateAccountList

permissions:
  id-token: write # OIDCでAWSにアクセス
  contents: read # actions/checkoutで必要

jobs:
  schemaspy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: app & mysql
        run: docker compose up -d app mysql

      - name: Debug Docker containers
        run: docker ps

      # - name: Remove Vendor Directory
      #   run: docker exec application-app-1 rm -rf /src/vendor

      # - name: Clear Composer Cache
      #   run: docker exec application-app-1 composer clear-cache

      - name: Fix Permissions
      run: |
        docker exec application-app-1 chown -R www-data:www-data /src /src/vendor
        docker exec application-app-1 chmod -R 775 /src /src/vendor

    - name: Install Composer Dependencies
      run: |
        docker exec application-app-1 mkdir -p /tmp/composer
        docker exec application-app-1 COMPOSER_TMP_DIR=/tmp/composer composer install --prefer-dist --no-interaction --verbose

      # マイグレーションを実行
      - name: Run Migration
        run: docker exec application-app-1 php artisan migrate

      # SchemaSpyを実行
      - name: SchemaSpy
        run: docker compose up -d schemaspy

      # AWSに接続するための設定
      - name: Set up AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::722015880532:role/GitHubActionsRoll
          aws-region: ap-northeast-1 # 東京リージョン

      # S3にアップロード
      - name: Upload to S3
        run: |
          ls -la
          pwd
          ls -la ./documents/
          pwd
          ls -la documents/
          pwd
          ls -la documents/schemaspy
          aws s3 sync documents/schemaspy s3://wada-db-diagram --delete
