# SchemaspyでER図を生成してS3にアップロード
name: schemaspy

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - feature/CreateAccountList

permissions:
  id-token: write # OIDCでAWSにアクセス
  contents: read # actions/checkoutで必要

jobs:
  schemaspy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: app & mysql
        run: docker compose up -d app mysql

      # マイグレーションを実行
      - name: Migration
        run: echo "Migration step is skipped."

      # mysqlを作成した後に、マイグレーション実行して、その後にschemaspyかな
      # SchemaSpyを実行
      - name: SchemaSpy
        run: docker compose up -d schemaspy

      # AWSに接続するための設定
      - name: Set up AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::722015880532:role/GitHubActionsRoll
          aws-region: ap-northeast-1 # 東京リージョン

      # S3にアップロード
      - name: Upload to S3
        run: |
          aws s3 sync ./documents/schemaspy s3://wada-db-diagram --delete
